/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cinequest.notificationservice.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AchievementUnlocked extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3558840895997433130L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AchievementUnlocked\",\"namespace\":\"com.cinequest.notificationservice.events\",\"fields\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"userEmail\",\"type\":\"string\"},{\"name\":\"userName\",\"type\":\"string\"},{\"name\":\"badgeName\",\"type\":\"string\"},{\"name\":\"badgeLevel\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"earnedAt\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AchievementUnlocked> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AchievementUnlocked> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AchievementUnlocked> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AchievementUnlocked> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AchievementUnlocked> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AchievementUnlocked to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AchievementUnlocked from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AchievementUnlocked instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AchievementUnlocked fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence userId;
  private java.lang.CharSequence userEmail;
  private java.lang.CharSequence userName;
  private java.lang.CharSequence badgeName;
  private java.lang.CharSequence badgeLevel;
  private java.lang.CharSequence description;
  private java.lang.CharSequence earnedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AchievementUnlocked() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param userEmail The new value for userEmail
   * @param userName The new value for userName
   * @param badgeName The new value for badgeName
   * @param badgeLevel The new value for badgeLevel
   * @param description The new value for description
   * @param earnedAt The new value for earnedAt
   */
  public AchievementUnlocked(java.lang.CharSequence userId, java.lang.CharSequence userEmail, java.lang.CharSequence userName, java.lang.CharSequence badgeName, java.lang.CharSequence badgeLevel, java.lang.CharSequence description, java.lang.CharSequence earnedAt) {
    this.userId = userId;
    this.userEmail = userEmail;
    this.userName = userName;
    this.badgeName = badgeName;
    this.badgeLevel = badgeLevel;
    this.description = description;
    this.earnedAt = earnedAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return userEmail;
    case 2: return userName;
    case 3: return badgeName;
    case 4: return badgeLevel;
    case 5: return description;
    case 6: return earnedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.CharSequence)value$; break;
    case 1: userEmail = (java.lang.CharSequence)value$; break;
    case 2: userName = (java.lang.CharSequence)value$; break;
    case 3: badgeName = (java.lang.CharSequence)value$; break;
    case 4: badgeLevel = (java.lang.CharSequence)value$; break;
    case 5: description = (java.lang.CharSequence)value$; break;
    case 6: earnedAt = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'userEmail' field.
   * @return The value of the 'userEmail' field.
   */
  public java.lang.CharSequence getUserEmail() {
    return userEmail;
  }


  /**
   * Sets the value of the 'userEmail' field.
   * @param value the value to set.
   */
  public void setUserEmail(java.lang.CharSequence value) {
    this.userEmail = value;
  }

  /**
   * Gets the value of the 'userName' field.
   * @return The value of the 'userName' field.
   */
  public java.lang.CharSequence getUserName() {
    return userName;
  }


  /**
   * Sets the value of the 'userName' field.
   * @param value the value to set.
   */
  public void setUserName(java.lang.CharSequence value) {
    this.userName = value;
  }

  /**
   * Gets the value of the 'badgeName' field.
   * @return The value of the 'badgeName' field.
   */
  public java.lang.CharSequence getBadgeName() {
    return badgeName;
  }


  /**
   * Sets the value of the 'badgeName' field.
   * @param value the value to set.
   */
  public void setBadgeName(java.lang.CharSequence value) {
    this.badgeName = value;
  }

  /**
   * Gets the value of the 'badgeLevel' field.
   * @return The value of the 'badgeLevel' field.
   */
  public java.lang.CharSequence getBadgeLevel() {
    return badgeLevel;
  }


  /**
   * Sets the value of the 'badgeLevel' field.
   * @param value the value to set.
   */
  public void setBadgeLevel(java.lang.CharSequence value) {
    this.badgeLevel = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'earnedAt' field.
   * @return The value of the 'earnedAt' field.
   */
  public java.lang.CharSequence getEarnedAt() {
    return earnedAt;
  }


  /**
   * Sets the value of the 'earnedAt' field.
   * @param value the value to set.
   */
  public void setEarnedAt(java.lang.CharSequence value) {
    this.earnedAt = value;
  }

  /**
   * Creates a new AchievementUnlocked RecordBuilder.
   * @return A new AchievementUnlocked RecordBuilder
   */
  public static com.cinequest.notificationservice.events.AchievementUnlocked.Builder newBuilder() {
    return new com.cinequest.notificationservice.events.AchievementUnlocked.Builder();
  }

  /**
   * Creates a new AchievementUnlocked RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AchievementUnlocked RecordBuilder
   */
  public static com.cinequest.notificationservice.events.AchievementUnlocked.Builder newBuilder(com.cinequest.notificationservice.events.AchievementUnlocked.Builder other) {
    if (other == null) {
      return new com.cinequest.notificationservice.events.AchievementUnlocked.Builder();
    } else {
      return new com.cinequest.notificationservice.events.AchievementUnlocked.Builder(other);
    }
  }

  /**
   * Creates a new AchievementUnlocked RecordBuilder by copying an existing AchievementUnlocked instance.
   * @param other The existing instance to copy.
   * @return A new AchievementUnlocked RecordBuilder
   */
  public static com.cinequest.notificationservice.events.AchievementUnlocked.Builder newBuilder(com.cinequest.notificationservice.events.AchievementUnlocked other) {
    if (other == null) {
      return new com.cinequest.notificationservice.events.AchievementUnlocked.Builder();
    } else {
      return new com.cinequest.notificationservice.events.AchievementUnlocked.Builder(other);
    }
  }

  /**
   * RecordBuilder for AchievementUnlocked instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AchievementUnlocked>
    implements org.apache.avro.data.RecordBuilder<AchievementUnlocked> {

    private java.lang.CharSequence userId;
    private java.lang.CharSequence userEmail;
    private java.lang.CharSequence userName;
    private java.lang.CharSequence badgeName;
    private java.lang.CharSequence badgeLevel;
    private java.lang.CharSequence description;
    private java.lang.CharSequence earnedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cinequest.notificationservice.events.AchievementUnlocked.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.userEmail)) {
        this.userEmail = data().deepCopy(fields()[1].schema(), other.userEmail);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.userName)) {
        this.userName = data().deepCopy(fields()[2].schema(), other.userName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.badgeName)) {
        this.badgeName = data().deepCopy(fields()[3].schema(), other.badgeName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.badgeLevel)) {
        this.badgeLevel = data().deepCopy(fields()[4].schema(), other.badgeLevel);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.description)) {
        this.description = data().deepCopy(fields()[5].schema(), other.description);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.earnedAt)) {
        this.earnedAt = data().deepCopy(fields()[6].schema(), other.earnedAt);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing AchievementUnlocked instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cinequest.notificationservice.events.AchievementUnlocked other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userEmail)) {
        this.userEmail = data().deepCopy(fields()[1].schema(), other.userEmail);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userName)) {
        this.userName = data().deepCopy(fields()[2].schema(), other.userName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.badgeName)) {
        this.badgeName = data().deepCopy(fields()[3].schema(), other.badgeName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.badgeLevel)) {
        this.badgeLevel = data().deepCopy(fields()[4].schema(), other.badgeLevel);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.description)) {
        this.description = data().deepCopy(fields()[5].schema(), other.description);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.earnedAt)) {
        this.earnedAt = data().deepCopy(fields()[6].schema(), other.earnedAt);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.cinequest.notificationservice.events.AchievementUnlocked.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.cinequest.notificationservice.events.AchievementUnlocked.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'userEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserEmail() {
      return userEmail;
    }


    /**
      * Sets the value of the 'userEmail' field.
      * @param value The value of 'userEmail'.
      * @return This builder.
      */
    public com.cinequest.notificationservice.events.AchievementUnlocked.Builder setUserEmail(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.userEmail = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'userEmail' field has been set.
      * @return True if the 'userEmail' field has been set, false otherwise.
      */
    public boolean hasUserEmail() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'userEmail' field.
      * @return This builder.
      */
    public com.cinequest.notificationservice.events.AchievementUnlocked.Builder clearUserEmail() {
      userEmail = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'userName' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserName() {
      return userName;
    }


    /**
      * Sets the value of the 'userName' field.
      * @param value The value of 'userName'.
      * @return This builder.
      */
    public com.cinequest.notificationservice.events.AchievementUnlocked.Builder setUserName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.userName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'userName' field has been set.
      * @return True if the 'userName' field has been set, false otherwise.
      */
    public boolean hasUserName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'userName' field.
      * @return This builder.
      */
    public com.cinequest.notificationservice.events.AchievementUnlocked.Builder clearUserName() {
      userName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'badgeName' field.
      * @return The value.
      */
    public java.lang.CharSequence getBadgeName() {
      return badgeName;
    }


    /**
      * Sets the value of the 'badgeName' field.
      * @param value The value of 'badgeName'.
      * @return This builder.
      */
    public com.cinequest.notificationservice.events.AchievementUnlocked.Builder setBadgeName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.badgeName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'badgeName' field has been set.
      * @return True if the 'badgeName' field has been set, false otherwise.
      */
    public boolean hasBadgeName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'badgeName' field.
      * @return This builder.
      */
    public com.cinequest.notificationservice.events.AchievementUnlocked.Builder clearBadgeName() {
      badgeName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'badgeLevel' field.
      * @return The value.
      */
    public java.lang.CharSequence getBadgeLevel() {
      return badgeLevel;
    }


    /**
      * Sets the value of the 'badgeLevel' field.
      * @param value The value of 'badgeLevel'.
      * @return This builder.
      */
    public com.cinequest.notificationservice.events.AchievementUnlocked.Builder setBadgeLevel(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.badgeLevel = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'badgeLevel' field has been set.
      * @return True if the 'badgeLevel' field has been set, false otherwise.
      */
    public boolean hasBadgeLevel() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'badgeLevel' field.
      * @return This builder.
      */
    public com.cinequest.notificationservice.events.AchievementUnlocked.Builder clearBadgeLevel() {
      badgeLevel = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.cinequest.notificationservice.events.AchievementUnlocked.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.description = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public com.cinequest.notificationservice.events.AchievementUnlocked.Builder clearDescription() {
      description = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'earnedAt' field.
      * @return The value.
      */
    public java.lang.CharSequence getEarnedAt() {
      return earnedAt;
    }


    /**
      * Sets the value of the 'earnedAt' field.
      * @param value The value of 'earnedAt'.
      * @return This builder.
      */
    public com.cinequest.notificationservice.events.AchievementUnlocked.Builder setEarnedAt(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.earnedAt = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'earnedAt' field has been set.
      * @return True if the 'earnedAt' field has been set, false otherwise.
      */
    public boolean hasEarnedAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'earnedAt' field.
      * @return This builder.
      */
    public com.cinequest.notificationservice.events.AchievementUnlocked.Builder clearEarnedAt() {
      earnedAt = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AchievementUnlocked build() {
      try {
        AchievementUnlocked record = new AchievementUnlocked();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.userEmail = fieldSetFlags()[1] ? this.userEmail : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.userName = fieldSetFlags()[2] ? this.userName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.badgeName = fieldSetFlags()[3] ? this.badgeName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.badgeLevel = fieldSetFlags()[4] ? this.badgeLevel : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.description = fieldSetFlags()[5] ? this.description : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.earnedAt = fieldSetFlags()[6] ? this.earnedAt : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AchievementUnlocked>
    WRITER$ = (org.apache.avro.io.DatumWriter<AchievementUnlocked>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AchievementUnlocked>
    READER$ = (org.apache.avro.io.DatumReader<AchievementUnlocked>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.userId);

    out.writeString(this.userEmail);

    out.writeString(this.userName);

    out.writeString(this.badgeName);

    out.writeString(this.badgeLevel);

    out.writeString(this.description);

    out.writeString(this.earnedAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);

      this.userEmail = in.readString(this.userEmail instanceof Utf8 ? (Utf8)this.userEmail : null);

      this.userName = in.readString(this.userName instanceof Utf8 ? (Utf8)this.userName : null);

      this.badgeName = in.readString(this.badgeName instanceof Utf8 ? (Utf8)this.badgeName : null);

      this.badgeLevel = in.readString(this.badgeLevel instanceof Utf8 ? (Utf8)this.badgeLevel : null);

      this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);

      this.earnedAt = in.readString(this.earnedAt instanceof Utf8 ? (Utf8)this.earnedAt : null);

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);
          break;

        case 1:
          this.userEmail = in.readString(this.userEmail instanceof Utf8 ? (Utf8)this.userEmail : null);
          break;

        case 2:
          this.userName = in.readString(this.userName instanceof Utf8 ? (Utf8)this.userName : null);
          break;

        case 3:
          this.badgeName = in.readString(this.badgeName instanceof Utf8 ? (Utf8)this.badgeName : null);
          break;

        case 4:
          this.badgeLevel = in.readString(this.badgeLevel instanceof Utf8 ? (Utf8)this.badgeLevel : null);
          break;

        case 5:
          this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);
          break;

        case 6:
          this.earnedAt = in.readString(this.earnedAt instanceof Utf8 ? (Utf8)this.earnedAt : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










